/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CeDrawer {
        "close": () => Promise<void>;
        "header": string;
        "maskClosable": boolean;
        "open": () => Promise<void>;
        "placement": string;
        "showHeader": boolean;
        "visible": Boolean;
        "width": string;
    }
}
export interface CeDrawerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCeDrawerElement;
}
declare global {
    interface HTMLCeDrawerElement extends Components.CeDrawer, HTMLStencilElement {
    }
    var HTMLCeDrawerElement: {
        prototype: HTMLCeDrawerElement;
        new (): HTMLCeDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "ce-drawer": HTMLCeDrawerElement;
    }
}
declare namespace LocalJSX {
    interface CeDrawer {
        "header"?: string;
        "maskClosable"?: boolean;
        "onClosed"?: (event: CeDrawerCustomEvent<any>) => void;
        "placement"?: string;
        "showHeader"?: boolean;
        "visible"?: Boolean;
        "width"?: string;
    }
    interface IntrinsicElements {
        "ce-drawer": CeDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ce-drawer": LocalJSX.CeDrawer & JSXBase.HTMLAttributes<HTMLCeDrawerElement>;
        }
    }
}
